# Generated by Django 4.1.2 on 2022-11-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="creator",
        ),
    ]
