# Generated by Django 4.1.1 on 2022-10-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_remove_label_tasks_alter_label_creator"),
        ("tasks", "0003_alter_task_creator_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="labels.label"
            ),
        ),
    ]
