# Generated by Django 4.1.1 on 2022-10-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0002_alter_status_name"),
        ("tasks", "0004_remove_task_status_task_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="statuses.status",
                verbose_name="Назначенный статус",
            ),
        ),
    ]
