# Generated by Django 4.1.1 on 2022-10-22 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_remove_label_tasks_alter_label_creator"),
        ("tasks", "0006_alter_task_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasksLabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="labels.label"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "Метки задач",
                "ordering": ["task"],
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="labels",
        ),
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                through="tasks.TasksLabels",
                to="labels.label",
            ),
        ),
    ]
