# Generated by Django 4.1.1 on 2022-10-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_remove_label_tasks_alter_label_creator"),
        ("tasks", "0007_taskslabels_alter_task_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskslabels",
            options={
                "ordering": ["task"],
                "verbose_name": "Метка задачи",
                "verbose_name_plural": "Метки задач",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="tasks",
                through="tasks.TasksLabels",
                to="labels.label",
            ),
        ),
    ]
