# Generated by Django 4.1.1 on 2022-10-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0002_remove_label_tasks_alter_label_creator"),
        ("tasks", "0009_alter_taskslabels_label_alter_taskslabels_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                through="tasks.TasksLabels",
                to="labels.label",
            ),
        ),
    ]
