# Generated by Django 4.1.1 on 2022-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Имя статуса"
            ),
        ),
    ]
